import { StakeholderQuestion } from './types';

export const FALLBACK_QUESTIONS: StakeholderQuestion[] = [
  // STUDENT
  {
    id: 'q-student-1',
    category_id: '10000000-0000-0000-0000-000000000004',
    question_text: 'What do you expect most from the Institute?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-s1-1', question_id: 'q-student-1', option_label: 'Quality teaching', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-s1-2', question_id: 'q-student-1', option_label: 'Practical learning', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-s1-3', question_id: 'q-student-1', option_label: 'Placement', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-s1-4', question_id: 'q-student-1', option_label: 'Internships', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-s1-5', question_id: 'q-student-1', option_label: 'Industry exposure', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-s1-6', question_id: 'q-student-1', option_label: 'Emerging tech skills', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-s1-7', question_id: 'q-student-1', option_label: 'Research', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-s1-8', question_id: 'q-student-1', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-s1-9', question_id: 'q-student-1', option_label: 'Higher education guidance', option_group: 'option', sort_order: 9, is_active: true },
      { id: 'opt-s1-10', question_id: 'q-student-1', option_label: 'Soft skills', option_group: 'option', sort_order: 10, is_active: true },
      { id: 'opt-s1-11', question_id: 'q-student-1', option_label: 'Ethics', option_group: 'option', sort_order: 11, is_active: true },
      { id: 'opt-s1-12', question_id: 'q-student-1', option_label: 'Personality development', option_group: 'option', sort_order: 12, is_active: true },
    ],
  },
  {
    id: 'q-student-2',
    category_id: '10000000-0000-0000-0000-000000000004',
    question_text: 'Which skills should the Institute emphasize for your future career?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 2,
    is_active: true,
    options: [
      { id: 'opt-s2-1', question_id: 'q-student-2', option_label: 'Technical skills', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-s2-2', question_id: 'q-student-2', option_label: 'Problem solving', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-s2-3', question_id: 'q-student-2', option_label: 'Communication', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-s2-4', question_id: 'q-student-2', option_label: 'Teamwork', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-s2-5', question_id: 'q-student-2', option_label: 'Leadership', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-s2-6', question_id: 'q-student-2', option_label: 'Innovation', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-s2-7', question_id: 'q-student-2', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-s2-8', question_id: 'q-student-2', option_label: 'Digital/AI skills', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-s2-9', question_id: 'q-student-2', option_label: 'Professional ethics', option_group: 'option', sort_order: 9, is_active: true },
      { id: 'opt-s2-10', question_id: 'q-student-2', option_label: 'Lifelong learning', option_group: 'option', sort_order: 10, is_active: true },
    ],
  },
  {
    id: 'q-student-3',
    category_id: '10000000-0000-0000-0000-000000000004',
    question_text: 'What one improvement would you like to see in the Institute in the coming years?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },

  // FACULTY
  {
    id: 'q-faculty-1',
    category_id: '10000000-0000-0000-0000-000000000002',
    question_text: 'Which areas should the Institute strengthen to achieve academic excellence?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-f1-1', question_id: 'q-faculty-1', option_label: 'Teaching-learning process', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-f1-2', question_id: 'q-faculty-1', option_label: 'Research', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-f1-3', question_id: 'q-faculty-1', option_label: 'Sponsored projects', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-f1-4', question_id: 'q-faculty-1', option_label: 'Consultancy', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-f1-5', question_id: 'q-faculty-1', option_label: 'Innovation', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-f1-6', question_id: 'q-faculty-1', option_label: 'FDP', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-f1-7', question_id: 'q-faculty-1', option_label: 'Industry collaboration', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-f1-8', question_id: 'q-faculty-1', option_label: 'Interdisciplinary activities', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-f1-9', question_id: 'q-faculty-1', option_label: 'Digital technologies', option_group: 'option', sort_order: 9, is_active: true },
      { id: 'opt-f1-10', question_id: 'q-faculty-1', option_label: 'International collaboration', option_group: 'option', sort_order: 10, is_active: true },
      { id: 'opt-f1-11', question_id: 'q-faculty-1', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 11, is_active: true },
      { id: 'opt-f1-12', question_id: 'q-faculty-1', option_label: 'Infrastructure', option_group: 'option', sort_order: 12, is_active: true },
    ],
  },
  {
    id: 'q-faculty-2',
    category_id: '10000000-0000-0000-0000-000000000002',
    question_text: 'What institutional support would help faculty contribute more effectively?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 2,
    is_active: true,
    options: [],
  },
  {
    id: 'q-faculty-3',
    category_id: '10000000-0000-0000-0000-000000000002',
    question_text: 'What major theme should be reflected in the future Vision?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },

  // ALUMNI
  {
    id: 'q-alumni-1',
    category_id: '10000000-0000-0000-0000-000000000005',
    question_text: 'Based on your professional experience, which areas should the Institute strengthen?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-a1-1', question_id: 'q-alumni-1', option_label: 'Technical competency', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-a1-2', question_id: 'q-alumni-1', option_label: 'Practical knowledge', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-a1-3', question_id: 'q-alumni-1', option_label: 'Industry exposure', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-a1-4', question_id: 'q-alumni-1', option_label: 'Communication', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-a1-5', question_id: 'q-alumni-1', option_label: 'Leadership', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-a1-6', question_id: 'q-alumni-1', option_label: 'Research', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-a1-7', question_id: 'q-alumni-1', option_label: 'Innovation', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-a1-8', question_id: 'q-alumni-1', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-a1-9', question_id: 'q-alumni-1', option_label: 'Ethics', option_group: 'option', sort_order: 9, is_active: true },
      { id: 'opt-a1-10', question_id: 'q-alumni-1', option_label: 'Emerging technologies', option_group: 'option', sort_order: 10, is_active: true },
      { id: 'opt-a1-11', question_id: 'q-alumni-1', option_label: 'Global exposure', option_group: 'option', sort_order: 11, is_active: true },
      { id: 'opt-a1-12', question_id: 'q-alumni-1', option_label: 'Alumni interaction', option_group: 'option', sort_order: 12, is_active: true },
    ],
  },
  {
    id: 'q-alumni-2',
    category_id: '10000000-0000-0000-0000-000000000005',
    question_text: 'Which competencies gained during your studies have helped you most in your career?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 2,
    is_active: true,
    options: [],
  },
  {
    id: 'q-alumni-3',
    category_id: '10000000-0000-0000-0000-000000000005',
    question_text: 'How would you like the Institute to be recognized in the next 10–15 years?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },

  // EMPLOYER / INDUSTRY
  {
    id: 'q-employer-1',
    category_id: '10000000-0000-0000-0000-000000000003',
    question_text: 'Which qualities do you expect from graduates of our Institute?',
    question_type: 'multiple_choice_grid',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-e1-r1', question_id: 'q-employer-1', option_label: 'Strong technical knowledge', option_group: 'row', sort_order: 1, is_active: true },
      { id: 'opt-e1-r2', question_id: 'q-employer-1', option_label: 'Problem solving', option_group: 'row', sort_order: 2, is_active: true },
      { id: 'opt-e1-r3', question_id: 'q-employer-1', option_label: 'Practical skills', option_group: 'row', sort_order: 3, is_active: true },
      { id: 'opt-e1-r4', question_id: 'q-employer-1', option_label: 'Communication', option_group: 'row', sort_order: 4, is_active: true },
      { id: 'opt-e1-r5', question_id: 'q-employer-1', option_label: 'Teamwork', option_group: 'row', sort_order: 5, is_active: true },
      { id: 'opt-e1-r6', question_id: 'q-employer-1', option_label: 'Leadership', option_group: 'row', sort_order: 6, is_active: true },
      { id: 'opt-e1-r7', question_id: 'q-employer-1', option_label: 'Adaptability', option_group: 'row', sort_order: 7, is_active: true },
      { id: 'opt-e1-r8', question_id: 'q-employer-1', option_label: 'Emerging technologies', option_group: 'row', sort_order: 8, is_active: true },
      { id: 'opt-e1-r9', question_id: 'q-employer-1', option_label: 'Innovation', option_group: 'row', sort_order: 9, is_active: true },
      { id: 'opt-e1-r10', question_id: 'q-employer-1', option_label: 'Professional ethics', option_group: 'row', sort_order: 10, is_active: true },
      { id: 'opt-e1-r11', question_id: 'q-employer-1', option_label: 'Lifelong learning', option_group: 'row', sort_order: 11, is_active: true },

      { id: 'opt-e1-c1', question_id: 'q-employer-1', option_label: 'Not Important', option_group: 'column', sort_order: 1, is_active: true },
      { id: 'opt-e1-c2', question_id: 'q-employer-1', option_label: 'Somewhat Important', option_group: 'column', sort_order: 2, is_active: true },
      { id: 'opt-e1-c3', question_id: 'q-employer-1', option_label: 'Important', option_group: 'column', sort_order: 3, is_active: true },
      { id: 'opt-e1-c4', question_id: 'q-employer-1', option_label: 'Very Important', option_group: 'column', sort_order: 4, is_active: true },
    ],
  },
  {
    id: 'q-employer-2',
    category_id: '10000000-0000-0000-0000-000000000003',
    question_text: 'Which areas should the Institute strengthen to improve industry readiness?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 2,
    is_active: true,
    options: [
      { id: 'opt-e2-1', question_id: 'q-employer-2', option_label: 'Industry-oriented curriculum', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-e2-2', question_id: 'q-employer-2', option_label: 'Internships', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-e2-3', question_id: 'q-employer-2', option_label: 'Industry projects', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-e2-4', question_id: 'q-employer-2', option_label: 'Professional certifications', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-e2-5', question_id: 'q-employer-2', option_label: 'Emerging technology training', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-e2-6', question_id: 'q-employer-2', option_label: 'Soft skills', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-e2-7', question_id: 'q-employer-2', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-e2-8', question_id: 'q-employer-2', option_label: 'Research collaboration', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-e2-9', question_id: 'q-employer-2', option_label: 'Industry mentoring', option_group: 'option', sort_order: 9, is_active: true },
    ],
  },
  {
    id: 'q-employer-3',
    category_id: '10000000-0000-0000-0000-000000000003',
    question_text: 'What should be the major focus of the Institute over the next decade?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },

  // PARENT
  {
    id: 'q-parent-1',
    category_id: '10000000-0000-0000-0000-000000000006',
    question_text: 'What are your major expectations from the Institute?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-p1-1', question_id: 'q-parent-1', option_label: 'Quality education', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-p1-2', question_id: 'q-parent-1', option_label: 'Career opportunities', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-p1-3', question_id: 'q-parent-1', option_label: 'Discipline', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-p1-4', question_id: 'q-parent-1', option_label: 'Safe learning environment', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-p1-5', question_id: 'q-parent-1', option_label: 'Technical competence', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-p1-6', question_id: 'q-parent-1', option_label: 'Communication skills', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-p1-7', question_id: 'q-parent-1', option_label: 'Ethical values', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-p1-8', question_id: 'q-parent-1', option_label: 'Personality development', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-p1-9', question_id: 'q-parent-1', option_label: 'Higher education opportunities', option_group: 'option', sort_order: 9, is_active: true },
      { id: 'opt-p1-10', question_id: 'q-parent-1', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 10, is_active: true },
      { id: 'opt-p1-11', question_id: 'q-parent-1', option_label: 'Social responsibility', option_group: 'option', sort_order: 11, is_active: true },
    ],
  },
  {
    id: 'q-parent-2',
    category_id: '10000000-0000-0000-0000-000000000006',
    question_text: 'What qualities would you like students to develop by the time they graduate?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 2,
    is_active: true,
    options: [],
  },
  {
    id: 'q-parent-3',
    category_id: '10000000-0000-0000-0000-000000000006',
    question_text: 'What should the Institute prioritize for its future development?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },

  // MANAGEMENT
  {
    id: 'q-mgmt-1',
    category_id: '10000000-0000-0000-0000-000000000001',
    question_text: 'Which areas are most important for the long-term growth of the Institute?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-m1-1', question_id: 'q-mgmt-1', option_label: 'Academic excellence', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-m1-2', question_id: 'q-mgmt-1', option_label: 'Research excellence', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-m1-3', question_id: 'q-mgmt-1', option_label: 'Institutional reputation', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-m1-4', question_id: 'q-mgmt-1', option_label: 'Innovation', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-m1-5', question_id: 'q-mgmt-1', option_label: 'Entrepreneurship', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-m1-6', question_id: 'q-mgmt-1', option_label: 'Industry collaboration', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-m1-7', question_id: 'q-mgmt-1', option_label: 'Global recognition', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-m1-8', question_id: 'q-mgmt-1', option_label: 'Emerging technologies', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-m1-9', question_id: 'q-mgmt-1', option_label: 'Sustainability', option_group: 'option', sort_order: 9, is_active: true },
      { id: 'opt-m1-10', question_id: 'q-mgmt-1', option_label: 'Social responsibility', option_group: 'option', sort_order: 10, is_active: true },
      { id: 'opt-m1-11', question_id: 'q-mgmt-1', option_label: 'Governance', option_group: 'option', sort_order: 11, is_active: true },
      { id: 'opt-m1-12', question_id: 'q-mgmt-1', option_label: 'Infrastructure development', option_group: 'option', sort_order: 12, is_active: true },
    ],
  },
  {
    id: 'q-mgmt-2',
    category_id: '10000000-0000-0000-0000-000000000001',
    question_text: 'Where should the Institute position itself in the next 10–15 years?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 2,
    is_active: true,
    options: [],
  },
  {
    id: 'q-mgmt-3',
    category_id: '10000000-0000-0000-0000-000000000001',
    question_text: 'Which institutional values are most important for achieving academic excellence and societal responsibility?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },

  // SOCIETY
  {
    id: 'q-soc-1',
    category_id: '10000000-0000-0000-0000-000000000007',
    question_text: 'What contributions do you expect from an engineering institution to society?',
    question_type: 'checkboxes',
    is_required: true,
    sort_order: 1,
    is_active: true,
    options: [
      { id: 'opt-soc1-1', question_id: 'q-soc-1', option_label: 'Ethical professionals', option_group: 'option', sort_order: 1, is_active: true },
      { id: 'opt-soc1-2', question_id: 'q-soc-1', option_label: 'Sustainable solutions', option_group: 'option', sort_order: 2, is_active: true },
      { id: 'opt-soc1-3', question_id: 'q-soc-1', option_label: 'Community service', option_group: 'option', sort_order: 3, is_active: true },
      { id: 'opt-soc1-4', question_id: 'q-soc-1', option_label: 'Environmental responsibility', option_group: 'option', sort_order: 4, is_active: true },
      { id: 'opt-soc1-5', question_id: 'q-soc-1', option_label: 'Technology for societal problems', option_group: 'option', sort_order: 5, is_active: true },
      { id: 'opt-soc1-6', question_id: 'q-soc-1', option_label: 'Inclusive development', option_group: 'option', sort_order: 6, is_active: true },
      { id: 'opt-soc1-7', question_id: 'q-soc-1', option_label: 'Innovation for social benefit', option_group: 'option', sort_order: 7, is_active: true },
      { id: 'opt-soc1-8', question_id: 'q-soc-1', option_label: 'Employment generation', option_group: 'option', sort_order: 8, is_active: true },
      { id: 'opt-soc1-9', question_id: 'q-soc-1', option_label: 'National development', option_group: 'option', sort_order: 9, is_active: true },
    ],
  },
  {
    id: 'q-soc-2',
    category_id: '10000000-0000-0000-0000-000000000007',
    question_text: 'Which social responsibilities should be reflected in the Institute Mission?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 2,
    is_active: true,
    options: [],
  },
  {
    id: 'q-soc-3',
    category_id: '10000000-0000-0000-0000-000000000007',
    question_text: 'What should graduates contribute to society?',
    question_type: 'paragraph',
    is_required: false,
    sort_order: 3,
    is_active: true,
    options: [],
  },
];
